### ISSUE TITLE
LRO_PROXYAUTH with Kerberos/Negotiate

### ISSUE THREAD

**Issue by dandare100** [rpm-software-management/librepo#67]
At the moment the LRO_PROXYAUTH option sets CURLOPT_PROXYAUTH option on the libcurl handle to CURLAUTH_ANY or CURLAUTH_BASIC.

When the libcurl handle option is set to CURLAUTH_ANY and the client machine librepo is running on is behind a proxy that supports Negotiate (CURLAUTH_NEGOTIATE) (with Kerberos and NTLM), libcurl will not fallback to NTLM or BASIC if the client machine kerberos is not setup or setup incorrectly.

https://bugzilla.redhat.com/show_bug.cgi?id=1219199

Would you entertain another pull request where an LRO option (LRO_PROXY_NEG_DISABLE or LRO_PROXY_KERBEROS_DISABLE) is created that would override the CURLAUTH_ANY to exclude CURLAUTH_NEGOTIATE by subtracting it from the bitmask created by CURLAUTH_ANY?

It wouldn't change any current behavior if the option wasn't set. 
The way yum solved this problem was to disable the Kerberos libcurl auth options in "urlgrabber"

**Comment by Tojaj** [comment]
Hi, the ``LRO_PROXY_KERBEROS_DISABLE`` seems reasonable. I can add it. Once it's added you will need to ask guys from DNF to add a support for this option.

**Comment by Tojaj** [comment]
Or maybe I will add completely different option, and option that takes bitfield in the same way as libcurl.

**Comment by Tojaj** [comment]
Resolved, see commit:
https://github.com/rpm-software-management/librepo/commit/bfc05df2f74ad7038977ce4c6b1fd367ec1da430

**Comment by cgwalters** [comment]
This breaks the build with RHEL 7.2's libcurl-7.29.0-25.el7.x86_64:

```
builddir/build/BUILD/librepo-librepo-1.7.16-12-bfc05df2f74ad7038977ce4c6b1fd367ec1da430/librepo/handle.c:171:21: error: 'CURLAUTH_NEGOTIATE' undeclared (first use in this function)
         out_mask |= CURLAUTH_NEGOTIATE;
```

There is `CURLAUTH_GSSNEGOTIATE` though.

**Comment by Tojaj** [comment]
@cgwalters Thanks Colin! Fixed by 7620f124c5358c3f98f0e4056ad9e5b38852e63b

**Comment by dandare100** [comment]
Nice.
Thank you.
I like the meta symbol idea
